### ISSUE TITLE
where can we download   yolov5s.640-640.v.6.0.onnx

### ISSUE THREAD

**Issue by MyraBaba** [DefTruth/lite.ai.toolkit#164]
Hi,

I couldn't find the model for   std::string onnx_path = "../../../hub/onnx/cv/yolov5s.640-640.v.6.0.onnx";

thx

**Comment by DefTruth** [comment]
See the latest README.md, you can download the all the onnx files from docker hub now.

## Model Zoo.

<div id="lite.ai.toolkit-Model-Zoo"></div>
<div id="lite.ai.toolkit-2"></div>

*Lite.AI.ToolKit* contains *[70+](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.onnx.md)* AI models with *[500+](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.onnx.md)* frozen pretrained  files now. Most of the files are converted by myself. You can use it through *lite::cv::Type::Class* syntax, such as *[lite::cv::detection::YoloV5](#lite.ai.toolkit-object-detection)*. More details can be found at [Examples for Lite.AI.ToolKit](#lite.ai.toolkit-Examples-for-Lite.AI.ToolKit). Note, for Google Drive, I can not upload all the *.onnx files because of the storage limitation (15G).

|File|Baidu Drive|Google Drive|Docker Hub|Hub (Docs)|  
|:---:|:---:|:---:|:---:|:---:|
|ONNX|[Baidu Drive](https://pan.baidu.com/s/1elUGcx7CZkkjEoYhTMwTRQ) code: 8gin|[Google Drive](https://drive.google.com/drive/folders/1p6uBcxGeyS1exc-T61vL8YRhwjYL4iD2?usp=sharing)|[ONNX Docker v0.1.22.01.08 (28G)](https://hub.docker.com/repository/docker/qyjdefdocker/lite.ai.toolkit-onnx-hub)|[ONNX Hub](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.onnx.md)|    
|MNN|[Baidu Drive](https://pan.baidu.com/s/1KyO-bCYUv6qPq2M8BH_Okg) code: 9v63 |❔|[MNN Docker v0.1.22.01.08 (11G)](https://hub.docker.com/repository/docker/qyjdefdocker/lite.ai.toolkit-mnn-hub)|[MNN Hub](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.mnn.md)|  
|NCNN|[Baidu Drive](https://pan.baidu.com/s/1hlnqyNsFbMseGFWscgVhgQ) code: sc7f |❔|[NCNN Docker v0.1.22.01.08 (9G)](https://hub.docker.com/repository/docker/qyjdefdocker/lite.ai.toolkit-ncnn-hub)|[NCNN Hub](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.ncnn.md)|
|TNN|[Baidu Drive](https://pan.baidu.com/s/1lvM2YKyUbEc5HKVtqITpcw) code: 6o6k|❔|[TNN Docker v0.1.22.01.08 (11G)](https://hub.docker.com/repository/docker/qyjdefdocker/lite.ai.toolkit-tnn-hub)|[TNN Hub](https://github.com/DefTruth/lite.ai.toolkit/tree/main/docs/hub/lite.ai.toolkit.hub.tnn.md)|

```shell
  docker pull qyjdefdocker/lite.ai.toolkit-onnx-hub:v0.1.22.01.08  # (28G)
  docker pull qyjdefdocker/lite.ai.toolkit-mnn-hub:v0.1.22.01.08   # (11G)
  docker pull qyjdefdocker/lite.ai.toolkit-ncnn-hub:v0.1.22.01.08  # (9G)
  docker pull qyjdefdocker/lite.ai.toolkit-tnn-hub:v0.1.22.01.08   # (11G)
```

###  🔑️ How to download Model Zoo from Docker Hub?  
* Firstly, pull the image from docker hub.  
  ```shell
  docker pull qyjdefdocker/lite.ai.toolkit-mnn-hub:v0.1.22.01.08 # (11G)
  docker pull qyjdefdocker/lite.ai.toolkit-ncnn-hub:v0.1.22.01.08 # (9G)
  docker pull qyjdefdocker/lite.ai.toolkit-tnn-hub:v0.1.22.01.08 # (11G)
  docker pull qyjdefdocker/lite.ai.toolkit-onnx-hub:v0.1.22.01.08 # (28G)
  ```
* Secondly, run the container with local `share` dir using `docker run -idt xxx`. A minimum example will show you as follows.  
  * make a `share` dir in your local device.
  ```shell
  mkdir share # any name is ok.
  ```
  * write `run_mnn_docker_hub.sh` script like:
  ```shell
  #!/bin/bash  
  PORT1=6072
  PORT2=6084
  SERVICE_DIR=/Users/xxx/Desktop/your-path-to/share
  CONRAINER_DIR=/home/hub/share
  CONRAINER_NAME=mnn_docker_hub_d
  
  docker run -idt -p ${PORT2}:${PORT1} -v ${SERVICE_DIR}:${CONRAINER_DIR} --shm-size=16gb --name ${CONRAINER_NAME} qyjdefdocker/lite.ai.toolkit-mnn-hub:v0.1.22.01.08

  ```
* Finally, copy the model weights from `/home/hub/mnn/cv` to your local `share` dir. 
  ```shell
  # activate mnn docker.
  sh ./run_mnn_docker_hub.sh
  docker exec -it mnn_docker_hub_d /bin/bash
  # copy the models to the share dir.
  cd /home/hub 
  cp -rf mnn/cv share/
  ```

**Comment by MyraBaba** [comment]
@DefTruth  hi ,

I couldnt find the yolov5face-s-640x640.onnx model. is it added ? Other yolov5face models will be added also ?

**Comment by DefTruth** [comment]
> @DefTruth hi ,
> 
> I couldnt find the yolov5face-s-640x640.onnx model. is it added ? Other yolov5face models will be added also ?

it can be download from Baidu Driver now, but not include into the docker images. i will update the docker images some days  latter.

**Comment by MyraBaba** [comment]
When we can download  yolov5face  models ? We cant reach baidu drive.

Best

**Comment by DefTruth** [comment]
> @DefTruth When we can download yolov5face models ? We cant reach baidu drive.
> 
> Best

Hello, currrently, my family and I are celebrating Chinese New Year. When I'm free, I'll upload all the model files to docker hub ~ however, you can download the nano version of yolov5face onnx/mnn/ncnn/tnn model files from my demo project:  
* https://github.com/DefTruth/YOLO5Face.lite.ai.toolkit/tree/main/examples/hub

**Comment by DefTruth** [comment]
you can download the converted ONNX/MNN/NCNN/TNN files of YOLO5Face from docker hub now ~  
```shell
  docker pull qyjdefdocker/lite.ai.toolkit-onnx-hub:v0.1.22.02.02  # (400M) + YOLO5Face
  docker pull qyjdefdocker/lite.ai.toolkit-mnn-hub:v0.1.22.02.02   # (213M) + YOLO5Face
  docker pull qyjdefdocker/lite.ai.toolkit-ncnn-hub:v0.1.22.02.02  # (197M) + YOLO5Face
  docker pull qyjdefdocker/lite.ai.toolkit-tnn-hub:v0.1.22.02.02   # (217M) + YOLO5Face
```

**Comment by MyraBaba** [comment]
@DefTruth  thanks for models. I make a speed test wit "s" models and ncnn is x4 time ,  tnn is x2 times slower than mnn and onnx.
ncnn should be faster i assume.

**Comment by MyraBaba** [comment]
@DefTruth 
Hi I hope all is good at your end.

I saw yolov5m-face.pt model at [https://github.com/deepcam-cn/yolov5-face](https://github.com/deepcam-cn/yolov5-face) 
and the size is 169MB . Yours onnx converted one is yolov5face-m-640x640.onnx 87 MB. What are the differences ? Both are same quality or something different ? 

Best

**Comment by MyraBaba** [comment]
@DefTruth 

Hi,

I noticed that the yolov5Face models allways return score : 0.98....


same score. Do you know this ? or are you already updated ?
